# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g mocha
  pre_build:
    commands:
      - npm install
      - npm i -g @angular/cli
  build:
    commands:
      - cd client
      - npm install
      - ng build
  post_build:
    commands:
      - cd..
# Include only the files required for your application to run.
artifacts:
  files:
    - "**/*"
    - src/server.js
    - src/app.js
    - package.json
    - node_modules/**/*
  discard-paths: no
  base-directory: client/public
